export * from "discord.js"
export * from "./app.native.js"
export * from "./namespaces/utils.native.js"
export * from "./namespaces/colors.js"
export * from "./namespaces/sendMessage.js"
export * from "./namespaces/strad.js"
export * from "./namespaces/emojis.js"
export * from "./namespaces/middlewares.js"
export * from "./namespaces/keys.js"
export * from "./namespaces/canvas.js"

export * as Discord from "discord.js"
export * as utils from "./namespaces/utils.native.js"
export * as colors from "./namespaces/colors.js"
export * as sendMessage from "./namespaces/sendMessage.js"
export * as strad from "./namespaces/strad.js"
export * as emojis from "./namespaces/emojis.js"
export * as middlewares from "./namespaces/middlewares.js"
export * as keys from "./namespaces/keys.js"
export * as canvas from "./namespaces/canvas.js"
