export * from "discord.js"
export * from "./app.native"
export * from "./namespaces/utils.native"
export * from "./namespaces/colors"
export * from "./namespaces/sendMessage"
export * from "./namespaces/strad"
export * from "./namespaces/emojis"
export * from "./namespaces/middlewares"
export * from "./namespaces/keys"

export * as Discord from "discord.js"
export * as utils from "./namespaces/utils.native"
export * as colors from "./namespaces/colors"
export * as sendMessage from "./namespaces/sendMessage"
export * as strad from "./namespaces/strad"
export * as emojis from "./namespaces/emojis"
export * as middlewares from "./namespaces/middlewares"
export * as keys from "./namespaces/keys"
